[server]
maxUploadSize = 3000
maxMessageSize = 3000
fileWatcherType = "none"
enableCORS = false
enableXsrfProtection = false
runOnSave = false

address = "0.0.0.0"
port = 8501
headless = true
fileWatcherType = "none"

[browser]
gatherUsageStats = false





